
const data = {
    products: [
      {
        id: '1',
        name: 'apple',
        price: 60,
        image: 'images/fruits/apple.jpg',
        category: "fruit",
      },
      {
        id: '2',
        name: 'banana',
        price: 40,
        image: "images/fruits/banana.png",
        category: "fruit",
        popular: true,
      },
      {
        id: '3',
        name: 'grape',
        price: 45,
        image: 'images/fruits/uva.jpeg',
        category: "fruit",
      },
      {
        id: '4',
        name: "lime",
        price: 35,
        image: 'images/fruits/lime.jpeg',
        category: "fruit",
        
      },
      {
        id: '5',
        name: 'orange',
        price: 40,
        image: 'images/fruits/orange.jpeg',
        category: "fruit",
        popular: true,
      },
      {
        id: '6',
        name: 'watermelon',
        price: 110,
        image: 'images/fruits/watermelon.jpg',
        category: "fruit",
      },
      {
        id: '7',
        name: 'pineapple',
        price: 80,
        image: 'images/fruits/pineapple.jpg',
        category: "fruit",
      },
      {
        id: '8',
        name: 'avocado',
        price: 120,
        image: 'images/fruits/avocado.jpg',
        category: "fruit",
        popular: true,
      },
      {
        id: '9',
        name: 'pear',
        price: 80,
        image: 'images/fruits/pear.jpg',
        category: "fruit",
      },
      {
        id: '55',
        name: 'tomato',
        price: 40,
        image: 'images/vegetables/tomato.jpg',
        category: "fruit",
        popular: true,
      },
      {
        id: '10',
        name: 'carrot',
        price: 30,
        image: 'images/vegetables/carrot.jpg',
        category: "vegetables",
        popular: true,
      },
      {
        id: '11',
        name: 'broccolli',
        price: 90,
        image: 'images/vegetables/Broccolli.jpg',
        category: "vegetables",
        popular: true,
      },
      {
        id: '12',
        name: 'potato',
        price: 35,
        image: 'images/vegetables/potato.jpg',
        category: "vegetables",
      },
      {
        id: '13',
        name: 'lettuce',
        price: 50,
        image: 'images/vegetables/Lettuce-2.jpg',
        category: "vegetables",
        popular: true,
      },
      {
        id: '14',
        name: 'eggplant',
        price: 50,
        image: 'images/vegetables/Eggplant.jpg',
        category: "vegetables",
      },
      {
        id: '15',
        name: 'pumpkin',
        price: 50,
        image: 'images/vegetables/Pumpkin.jpg',
        category: "vegetables",
      },
      {
        id: '16',
        name: 'onion',
        price: 50,
        image: 'images/vegetables/Onion.webp',
        category: "vegetables",
        popular: true,
      },
      {
        id: '17',
        name: 'oatmeal',
        price: 50,
        image: 'images/grains/avena.jpg',
        category: "grains",
      },
      {
        id: '18',
        name: 'integral rice',
        price: 150,
        image: 'images/grains/Integral rice.jpg',
        category: "grains",
      },
      {
        id: '19',
        name: 'granola',
        price: 300,
        image: 'images/grains/Granola.jpg',
        category: "grains",
        popular: true,
      },
      {
        id: '20',
        name: 'cereal',
        price: 200,
        image: 'images/grains/Cereal.jpg',
        category: "grains",
      },
      {
        id: '21',
        name: 'leche de soja',
        price: 500,
        image: 'images/milk/leche-soja.png',
        category: "milk",
        popular: true,
      },
      
      {
        id: '23',
        name: 'leche de coco',
        price: 500,
        image: 'images/milk/Leche decoco.jpg',
        category: "milk",
      },
      {
        id: '24',
        name: 'chickpea',
        price: 300,
        image: 'images/legumes/chickpeas.jpeg',
        category: "legumes",
      },
      {
        id: '25',
        name: 'beans',
        price: 180,
        image: 'images/legumes/Beans.jpg',
        category: "legumes",
      },
      {
        id: '26',
        name: 'lentils',
        price: 200,
        image: 'images/legumes/lentils.jpg',
        category: "legumes",
      },
      {
        id: '27',
        name: 'almonds',
        price: 200,
        image: 'images/nuts/almonds.jpg',
        category: "nuts",
        popular: true,
      },
      {
        id: '28',
        name: 'hazelnuts',
        price: 100,
        image: 'images/nuts/hazelNuts.jpg',
        category: "nuts",
      },
      {
        id: '29',
        name: 'walnuts',
        price: 250,
        image: 'images/nuts/walNuts.jpg',
        category: "nuts",
      },
      {
        id: '30',
        name: 'peanuts',
        price: 250,
        image: 'images/nuts/peaNuts.jpg',
        category: "nuts",
      },
      {
        id: '40',
        name: 'cinnamon',
        price: 325,
        image: 'images/spices/Cinnamon.jpg',
        category: "spices",
      },
      {
        id: '41',
        name: 'cumin',
        price: 100,
        image: 'images/spices/Cumin.jpg',
        category: "spices",
      },
      {
        id: '42',
        name: 'paprika',
        price: 290,
        image: 'images/spices/Paprika.jpg',
        category: "spices",
      },
      {
        id: '43',
        name: 'garlic powder',
        price: 190,
        image: 'images/spices/Garlic powder.webp',
        category: "spices",
      },
      {
        id: '44',
        name: 'nutmeg',
        price: 80,
        image: 'images/spices/Nutmeg.jpg',
        category: "spices",
      },
      {
        id: '45',
        name: 'rosemary',
        price: 90,
        image: 'images/spices/Rosemary.jpg',
        category: "spices",
      },
      {
        id: '46',
        name: 'basil',
        price: 300,
        image: 'images/spices/Basil.jpg',
        category: "spices",
      },
      {
        id: '47',
        name: 'parsley',
        price: 400,
        image: 'images/spices/Parsley.jpg',
        category: "spices",
      },
      {
        id: '48',
        name: 'oregano',
        price: 150,
        image: 'images/spices/Oregano.webp',
        category: "spices",
      },
      {
        id: '49',
        name: 'black pepper',
        price: 500,
        image: 'images/spices/Black pepper.jpg',
        category: "spices",
      },
      {
        id: '50',
        name: 'saffron',
        price: 1200,
        image: 'images/spices/Saffron.png',
        category: "spices",
      },
      
      
    ],
    categories:[
      {id:"a",
      name:"fruit",
      image:"images/categories/fruits.jpg"    
      },
      {id:"b",
      name:"vegetables",
      image:"images/categories/vegetables.jpg",    
      },
      {id:"c",
      name:"grains",
      image:"images/categories/grains.jpg",     
      },
      {id:"d",
      name:"milk",
      image:"images/categories/milk.jpg",     
      },
      {id:"e",
      name:"legumes",
      image:"images/categories/legumes.jpg",     
      },
      {id:"f",
      name:"nuts",
      image:"images/categories/nuts.jpg",     
      },
      { 
        id:"g",
        name:"spices",
        image:"images/categories/spices.jpg",     
      },
      
    ]
  };
  export default data;