

const data = {
    products: [
      {
        id: '1',
        name: 'Apple',
        price: 1400,
        image: '../src/assets/images/fruits/apple.jpg',
        category: "Fruit",
      },
      {
        id: '2',
        name: 'Banana',
        price: 2400,
        image: "../src/assets/images/fruits/banana.png",
        category: "Fruit",
        popular: true,
      },
      {
        id: '3',
        name: 'Grape',
        price: 1000,
        image: '../src/assets/images/fruits/uva.jpeg',
        category: "Fruit",
      },
      {
        id: '4',
        name: "Lime",
        price: 1000,
        image: '../src/assets/images/fruits/lime.jpeg',
        category: "Fruit",
        popular: true,
      },
      {
        id: '5',
        name: 'orange',
        price: 300,
        image: '../src/assets/images/fruits/orange.jpeg',
        category: "Fruit",
        popular: true,
      },
      {
        id: '6',
        name: 'Watermelon',
        price: 600,
        image: '../src/assets/images/fruits/watermelon.jpg',
        category: "Fruit",
      },
      {
        id: '7',
        name: 'Pineapple',
        price: 500,
        image: '../src/assets/images/fruits/pineapple.jpg',
        category: "Fruit",
      },
      {
        id: '8',
        name: 'Avocado',
        price: 500,
        image: '../src/assets/images/fruits/avocado.jpg',
        category: "Fruit",
        popular: true,
      },
      {
        id: '9',
        name: 'Pear',
        price: 500,
        image: '../src/assets/images/fruits/pear.jpg',
        category: "Fruit",
      },
      {
        id: '55',
        name: 'Tomato',
        price: 500,
        image: '../src/assets/images/vegetables/tomato.jpg',
        category: "Fruit",
        popular: true,
      },
      {
        id: '10',
        name: 'Carrot',
        price: 500,
        image: '../src/assets/images/vegetables/carrot.jpg',
        category: "Vegetables",
        popular: true,
      },
      {
        id: '11',
        name: 'Broccolli',
        price: 500,
        image: '../src/assets/images/vegetables/Broccolli.jpg',
        category: "Vegetables",
        popular: true,
      },
      {
        id: '12',
        name: 'Potato',
        price: 500,
        image: '../src/assets/images/vegetables/potato.jpg',
        category: "Vegetables",
      },
      {
        id: '13',
        name: 'Lettuce',
        price: 500,
        image: '../src/assets/images/vegetables/Lettuce-2.jpg',
        category: "Vegetables",
        popular: true,
      },
      {
        id: '14',
        name: 'Eggplant',
        price: 500,
        image: '../src/assets/images/vegetables/Eggplant.jpg',
        category: "Vegetables",
      },
      {
        id: '15',
        name: 'Pumpkin',
        price: 500,
        image: '../src/assets/images/vegetables/Pumpkin.jpg',
        category: "Vegetables",
      },
      {
        id: '16',
        name: 'Onion',
        price: 500,
        image: '../src/assets/images/vegetables/Onion.webp',
        category: "Vegetables",
        popular: true,
      },
      {
        id: '17',
        name: 'Oatmeal',
        price: 500,
        image: '../src/assets/images/grains/avena.jpg',
        category: "Grains",
      },
      {
        id: '18',
        name: 'Integral rice',
        price: 500,
        image: '../src/assets/images/grains/Integral rice.jpg',
        category: "Grains",
      },
      {
        id: '19',
        name: 'Granola',
        price: 500,
        image: '../src/assets/images/grains/Granola.jpg',
        category: "Grains",
        popular: true,
      },
      {
        id: '20',
        name: 'Cereal',
        price: 500,
        image: '../src/assets/images/grains/Cereal.jpg',
        category: "Grains",
      },
      {
        id: '21',
        name: 'Leche de soja',
        price: 500,
        image: '../src/assets/images/milk/leche-soja.png',
        category: "Milk",
      },
      {
        id: '22',
        name: 'Leche de almendras',
        price: 500,
        image: '../src/assets/images/milk/Leche de almendras.jpg',
        category: "Milk",
        popular: true,
      },
      {
        id: '23',
        name: 'Leche de coco',
        price: 500,
        image: '../src/assets/images/milk/Leche decoco.jpg',
        category: "Milk",
      },
      {
        id: '24',
        name: 'Chickpea',
        price: 500,
        image: '../src/assets/images/legumes/chickpeas.jpeg',
        category: "Legumes",
      },
      {
        id: '25',
        name: 'Beans',
        price: 500,
        image: '../src/assets/images/legumes/Beans.jpg',
        category: "Legumes",
      },
      {
        id: '26',
        name: 'lentils',
        price: 500,
        image: '../src/assets/images/legumes/lentils.jpg',
        category: "Legumes",
      },
      {
        id: '27',
        name: 'almonds',
        price: 500,
        image: '../src/assets/images/nuts/almonds.jpg',
        category: "Nuts",
        popular: true,
      },
      {
        id: '28',
        name: 'hazelNuts',
        price: 500,
        image: '../src/assets/images/nuts/hazelNuts.jpg',
        category: "Nuts",
      },
      {
        id: '29',
        name: 'walNuts',
        price: 500,
        image: '../src/assets/images/nuts/walNuts.jpg',
        category: "Nuts",
      },
      {
        id: '30',
        name: 'peaNuts',
        price: 500,
        image: '../src/assets/images/nuts/peaNuts.jpg',
        category: "Nuts",
      },
      {
        id: '40',
        name: 'Cinnamon',
        price: 500,
        image: '../src/assets/images/spices/Cinnamon.jpg',
        category: "Spices",
      },
      {
        id: '41',
        name: 'Cumin',
        price: 500,
        image: '../src/assets/images/spices/Cumin.jpg',
        category: "Spices",
      },
      {
        id: '42',
        name: 'Paprika',
        price: 500,
        image: '../src/assets/images/spices/Paprika.jpg',
        category: "Spices",
      },
      {
        id: '43',
        name: 'Garlic powder',
        price: 500,
        image: '../src/assets/images/spices/Garlic powder.webp',
        category: "Spices",
      },
      {
        id: '44',
        name: 'Nutmeg',
        price: 500,
        image: '../src/assets/images/spices/Nutmeg.jpg',
        category: "Spices",
      },
      {
        id: '45',
        name: 'Rosemary',
        price: 500,
        image: '../src/assets/images/spices/Rosemary.jpg',
        category: "Spices",
      },
      {
        id: '46',
        name: 'Basil',
        price: 500,
        image: '../src/assets/images/spices/Basil.jpg',
        category: "Spices",
      },
      {
        id: '47',
        name: 'Parsley',
        price: 500,
        image: '../src/assets/images/spices/Parsley.jpg',
        category: "Spices",
      },
      {
        id: '48',
        name: 'Oregano',
        price: 500,
        image: '../src/assets/images/spices/Oregano.webp',
        category: "Spices",
      },
      {
        id: '49',
        name: 'Black pepper',
        price: 500,
        image: '../src/assets/images/spices/Black pepper.jpg',
        category: "Spices",
      },
      {
        id: '50',
        name: 'Saffron',
        price: 500,
        image: '../src/assets/images/spices/Saffron.png',
        category: "Spices",
      },
      {
        id: '51',
        name: 'Parsley',
        price: 500,
        image: '../src/assets/images/spices/Parsley.jpg',
        category: "Snacks",
      },
      
    ],
    categories:[
      {id:"a",
      name:"Fruit",
      image:"https://store-images.s-microsoft.com/image/apps.48526.13510798886601649.29155bfc-29e7-4cbc-8f3c-07cfce0201a2.9a85b5d2-68a0-426f-a9fe-36478f201bbe?mode=scale&q=90&h=400&w=800&background=%23464646"    
      },
      {id:"b",
      name:"Vegetables",
      image:"https://www.collinsdictionary.com/images/full/vegetable_82806697.jpg",    
      },
      {id:"c",
      name:"Grains",
      image:"https://previews.123rf.com/images/milkos/milkos1810/milkos181001115/111009426-set-of-various-grains-cereals-Legumes-beans-and-lentils-in-bowls-isolated.jpg",     
      },
      {id:"d",
      name:"Milk",
      image:"https://alpina.com/media/mageplaza/blog/post/l/a/la-leche_descremada-y-la-leche-deslactosadas-son_iguales-3.jpg",     
      },
      {id:"e",
      name:"Legumes",
      image:"https://thevedikshop.com/wp-content/uploads/2021/03/Legumes-beans-assortment-different-bowls-light-stone-top-view-healthy-vegan-protein-food-scaled.jpg",     
      },
      {id:"f",
      name:"Nuts",
      image:"https://m.media-amazon.com/images/I/71AM3JSOiTL._SL1500_.jpg",     
      },
      { 
        id:"g",
        name:"Spices",
        image:"https://kansaslivingmagazine.com/sites/default/files/styles/maximum/public/gettyimages-1215958963.jpg?itok=EJ8Webc6",     
      },
      {
        id:"h",
        name:"Snacks",
        image:"https://www.webconsultas.com/sites/default/files/styles/wc_adaptive_image__medium/public/mezcla-frutos-secos_0.jpg",     
      },
    ]
  };
  export default data;